<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerSy3xrae\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerSy3xrae/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerSy3xrae\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSy3xrae\appDevDebugProjectContainer();
